---
abstract: "A Simple PTY connection to Wolfram's Mathematica"
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  File::Which: 0
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Mathematica
no_index:
  file:
    - README.pod
provides:
  Math::Mathematica:
    file: lib/Math/Mathematica.pm
    version: 0.002
requires:
  IO::Pty::Easy: 0
resources:
  bugtracker: http://github.com/jberger/Math-Mathematica/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Math-Mathematica
version: 0.002
